- name: Symlink local fonts
  file:
    src: /usr/local/share/fonts/
    dest: /usr/share/fonts/local
    state: link
    force: True

- name: Copy Windows fonts
  copy:
    src: 'WindowsFonts/{{ item }}'
    dest: /usr/local/share/fonts/WindowsFonts/
    mode: 0755
  notify: Refresh fontconfig cache
  with_items:
    - arialbd.ttf
    - arialbi.ttf
    - ariali.ttf
    - arial.ttf
    - ariblk.ttf
    - calibrib.ttf
    - calibrii.ttf
    - calibrili.ttf
    - calibril.ttf
    - calibri.ttf
    - calibriz.ttf
    - cambriab.ttf
    - cambriai.ttf
    - cambria.ttc
    - cambriaz.ttf
    - Candarab.ttf
    - Candarai.ttf
    - Candara.ttf
    - Candaraz.ttf
    - comicbd.ttf
    - comici.ttf
    - comic.ttf
    - comicz.ttf
    - consolab.ttf
    - consolai.ttf
    - consola.ttf
    - consolaz.ttf
    - constanb.ttf
    - constani.ttf
    - constan.ttf
    - constanz.ttf
    - corbelb.ttf
    - corbeli.ttf
    - corbel.ttf
    - corbelz.ttf
    - courbd.ttf
    - courbi.ttf
    - couri.ttf
    - cour.ttf
    - ebrimabd.ttf
    - ebrima.ttf
    - framdit.ttf
    - framd.ttf
    - Gabriola.ttf
    - gadugib.ttf
    - gadugi.ttf
    - georgiab.ttf
    - georgiai.ttf
    - georgia.ttf
    - georgiaz.ttf
    - himalaya.ttf
    - impact.ttf
    - javatext.ttf
    - l_10646.ttf
    - LeelaUIb.ttf
    - LeelawUI.ttf
    - LeelUIsl.ttf
    - lucon.ttf
    - malgunbd.ttf
    - malgunsl.ttf
    - malgun.ttf
    - marlett.ttf
    - micross.ttf
    - mingliub.ttc
    - mmrtextb.ttf
    - mmrtext.ttf
    - monbaiti.ttf
    - msgothic.ttc
    - msjhbd.ttc
    - msjhl.ttc
    - msjh.ttc
    - msyhbd.ttc
    - msyhl.ttc
    - msyh.ttc
    - msyi.ttf
    - mvboli.ttf
    - NirmalaB.ttf
    - NirmalaS.ttf
    - Nirmala.ttf
    - ntailub.ttf
    - ntailu.ttf
    - palabi.ttf
    - palab.ttf
    - palai.ttf
    - pala.ttf
    - phagspab.ttf
    - phagspa.ttf
    - segmdl2.ttf
    - segoeprb.ttf
    - segoepr.ttf
    - segoescb.ttf
    - segoesc.ttf
    - segoeuib.ttf
    - segoeuii.ttf
    - segoeuil.ttf
    - segoeuisl.ttf
    - segoeui.ttf
    - segoeuiz.ttf
    - seguibli.ttf
    - seguibl.ttf
    - seguiemj.ttf
    - seguihis.ttf
    - seguili.ttf
    - seguisbi.ttf
    - seguisb.ttf
    - seguisli.ttf
    - seguisym.ttf
    - simsunb.ttf
    - simsun.ttc
    - SitkaB.ttc
    - SitkaI.ttc
    - Sitka.ttc
    - SitkaZ.ttc
    - sylfaen.ttf
    - symbol.ttf
    - tahomabd.ttf
    - tahoma.ttf
    - taileb.ttf
    - taile.ttf
    - timesbd.ttf
    - timesbi.ttf
    - timesi.ttf
    - times.ttf
    - trebucbd.ttf
    - trebucbi.ttf
    - trebucit.ttf
    - trebuc.ttf
    - verdanab.ttf
    - verdanai.ttf
    - verdana.ttf
    - verdanaz.ttf
    - webdings.ttf
    - wingding.ttf
    - YuGothB.ttc
    - YuGothL.ttc
    - YuGothM.ttc
    - YuGothR.ttc
